import Luce.Model
import Mathlib.MeasureTheory.Constructions.BorelSpace.Real
import Mathlib.MeasureTheory.MeasurableSpace.Constructions

/-! # Section 2: approved predictability statement record

Source: `fixed_points.tex:569-579`, `eq:remaining-weight`,
`eq:predictable-p`, and the sentence asserting measurability before the draw.

The user approved this definition and proposition. This record remains
outside the production imports. `Luce.history_predictability` now proves it;
`audit/HistoryPredictability.lean` checks the production definition and
statement against this record by definitional equality.
-/

open MeasureTheory
universe u

namespace Luce.Section2Proposal

/-- The sigma algebra generated by the first `m` draws.
The label space has the discrete sigma algebra `⊤`. A zero-based position
`j` is among the first `m` draws exactly when `j.val < m`.
-/
def drawHistory {Ω : Type u} {n : ℕ}
    (π : Ω → Equiv.Perm (Fin n)) (m : ℕ) : MeasurableSpace Ω :=
  ⨆ j : Fin n, ⨆ (_ : j.val < m),
    MeasurableSpace.comap (fun ω => π ω j) ⊤

/-- Approved type of the Section 2 measurability assertion.
The Lean position `k` represents the paper's position `k.val + 1`, so its
pre-draw history contains exactly `k.val` draws.
-/
def PredictabilityStatement : Prop :=
  ∀ {Ω : Type u} {n : ℕ} (w : Weights n)
    (π : Ω → Equiv.Perm (Fin n)) (k : Fin n),
    Measurable[drawHistory π k.val]
      (fun ω => if k ≤ (π ω).symm k then (1 : ℝ) else 0) ∧
    Measurable[drawHistory π k.val]
      (fun ω => w.total (remaining (π ω) k))

#print drawHistory
#print PredictabilityStatement
#print axioms drawHistory
#print axioms PredictabilityStatement

end Luce.Section2Proposal
