import Luce.FinitePointMeasure
import Luce.FinitePoissonLaw
import Mathlib.Topology.ContinuousMap.StoneWeierstrass
import Mathlib.Analysis.SpecialFunctions.Exp

/-! # Laplace coordinates of finite point measures

The weak topology is viewed through its actual moment map. The spatial
space is only topological; no Hausdorff or countability condition is used.
-/

open MeasureTheory Topology
open scoped NNReal ENNReal BigOperators BoundedContinuousFunction

namespace Luce

variable {X : Type*} [TopologicalSpace X]

abbrev PointMomentSpace (X : Type*) [TopologicalSpace X] :=
  WeakDual ℝ≥0 (X →ᵇ ℝ≥0)

/-- A bounded nonnegative spatial test gives a continuous Laplace coordinate
on the moment space. -/
noncomputable def momentLaplace (g : X →ᵇ ℝ≥0) : C(PointMomentSpace X, ℝ) :=
  ⟨fun u => Real.exp (-(u g : ℝ)),
    Real.continuous_exp.comp ((NNReal.continuous_coe.comp
      (WeakDual.eval_continuous g)).neg)⟩

@[simp] theorem momentLaplace_apply (g : X →ᵇ ℝ≥0) (u : PointMomentSpace X) :
    momentLaplace g u = Real.exp (-(u g : ℝ)) := rfl

@[simp] theorem momentLaplace_zero : momentLaplace (0 : X →ᵇ ℝ≥0) = 1 := by
  ext u
  simp [momentLaplace]

theorem momentLaplace_add (g h : X →ᵇ ℝ≥0) :
    momentLaplace (g + h) = momentLaplace g * momentLaplace h := by
  ext u
  simp [momentLaplace, map_add, Real.exp_add, mul_comm]

/-- Products of Laplace coordinates are again Laplace coordinates. -/
noncomputable def momentLaplaceMonoid : Submonoid C(PointMomentSpace X, ℝ) where
  carrier := Set.range momentLaplace
  one_mem' := ⟨0, momentLaplace_zero⟩
  mul_mem' := by
    rintro a b ⟨g, rfl⟩ ⟨h, rfl⟩
    exact ⟨g + h, momentLaplace_add g h⟩

/-- The algebra generated by the Laplace coordinates. -/
noncomputable def momentLaplaceAlgebra : Subalgebra ℝ C(PointMomentSpace X, ℝ) :=
  Algebra.adjoin ℝ (momentLaplaceMonoid (X := X) : Set C(PointMomentSpace X, ℝ))

theorem momentLaplaceAlgebra_eq_span :
    (momentLaplaceAlgebra (X := X)).toSubmodule =
      Submodule.span ℝ (Set.range (momentLaplace (X := X))) := by
  rw [momentLaplaceAlgebra, Algebra.adjoin_eq_span, Submonoid.closure_eq]
  rfl

theorem momentLaplaceAlgebra_separatesPoints :
    (momentLaplaceAlgebra (X := X)).SeparatesPoints := by
  intro u v huv
  obtain ⟨g, hg⟩ := DFunLike.ne_iff.mp huv
  refine ⟨momentLaplace g, ⟨momentLaplace g, Algebra.subset_adjoin ⟨g, rfl⟩, rfl⟩, ?_⟩
  intro h
  apply hg
  exact NNReal.coe_inj.mp (neg_injective (Real.exp_injective h))

theorem norm_momentLaplace_le_one (g : X →ᵇ ℝ≥0) (u : PointMomentSpace X) :
    ‖momentLaplace g u‖ ≤ 1 := by
  rw [momentLaplace_apply, Real.norm_eq_abs, abs_of_pos (Real.exp_pos _)]
  exact Real.exp_le_one_iff.mpr (neg_nonpos.mpr (u g).coe_nonneg)

/-- Every Laplace polynomial is globally bounded, before restricting to
any compact set of point measures. -/
theorem momentLaplaceAlgebra_bounded (a : C(PointMomentSpace X, ℝ))
    (ha : a ∈ momentLaplaceAlgebra) :
    ∃ C : ℝ, ∀ u, ‖a u‖ ≤ C := by
  have ha' : a ∈ Submodule.span ℝ (Set.range (momentLaplace (X := X))) := by
    rw [← momentLaplaceAlgebra_eq_span]
    exact ha
  clear ha
  induction ha' using Submodule.span_induction with
  | mem a ha =>
    obtain ⟨g, rfl⟩ := ha
    exact ⟨1, norm_momentLaplace_le_one g⟩
  | zero => exact ⟨0, by simp⟩
  | add a b _ _ ha hb =>
    obtain ⟨A, hA⟩ := ha
    obtain ⟨B, hB⟩ := hb
    exact ⟨A + B, fun u => (norm_add_le (a u) (b u)).trans (add_le_add (hA u) (hB u))⟩
  | smul c a _ ha =>
    obtain ⟨A, hA⟩ := ha
    refine ⟨|c| * A, fun u => ?_⟩
    simpa only [ContinuousMap.smul_apply, norm_smul, Real.norm_eq_abs] using
      mul_le_mul_of_nonneg_left (hA u) (abs_nonneg c)

section PointMeasures

variable [MeasurableSpace X] [OpensMeasurableSpace X]

/-- The weak moment map on actual finite point measures. -/
noncomputable def pointMoment (μ : FinitePointMeasure X) : PointMomentSpace X :=
  FiniteMeasure.toWeakDualBCNN μ.toFiniteMeasure

theorem continuous_pointMoment : Continuous (pointMoment (X := X)) :=
  FiniteMeasure.toWeakDualBCNN_continuous.comp
    FinitePointMeasure.continuous_toFiniteMeasure

theorem isInducing_pointMoment : IsInducing (pointMoment (X := X)) := by
  have h₁ : IsInducing (FinitePointMeasure.toFiniteMeasure (X := X)) :=
    IsInducing.subtypeVal
  have h₂ : IsInducing (FiniteMeasure.toWeakDualBCNN (Ω := X)) := ⟨rfl⟩
  exact h₂.comp h₁

theorem measurable_momentLaplace_pointMoment (g : X →ᵇ ℝ≥0) :
    Measurable (fun μ : FinitePointMeasure X => momentLaplace g (pointMoment μ)) := by
  have hg : Measurable (fun x : X => (g x : ℝ≥0∞)) :=
    g.measurable_coe_ennreal_comp
  have hi := (Measure.measurable_lintegral hg).comp
    FinitePointMeasure.measurable_toMeasure
  exact hi.ennreal_toReal.neg.exp

theorem measurable_momentLaplaceAlgebra_pointMoment (a : C(PointMomentSpace X, ℝ))
    (ha : a ∈ momentLaplaceAlgebra) :
    Measurable (fun μ : FinitePointMeasure X => a (pointMoment μ)) := by
  have ha' : a ∈ Submodule.span ℝ (Set.range (momentLaplace (X := X))) := by
    rw [← momentLaplaceAlgebra_eq_span]
    exact ha
  clear ha
  induction ha' using Submodule.span_induction with
  | mem a ha =>
    obtain ⟨g, rfl⟩ := ha
    exact measurable_momentLaplace_pointMoment g
  | zero => exact measurable_const
  | add a b _ _ ha hb => exact ha.add hb
  | smul c a _ ha => exact ha.const_smul c

theorem momentLaplace_pointMoment_eq_pointLaplace (g : X →ᵇ ℝ≥0)
    (μ : FinitePointMeasure X) :
    momentLaplace g (pointMoment μ) = pointLaplace (fun x => (g x : ℝ)) μ := by
  change Real.exp (-((∫⁻ x, (g x : ℝ≥0∞) ∂(μ.toFiniteMeasure : Measure X)).toReal)) = _
  rw [BoundedContinuousFunction.toReal_lintegral_coe_eq_integral]
  rfl

end PointMeasures
end Luce

