import Luce.Section2DrawHistory
import Luce.Section2DrawHistoryPermutation

/-!
# Finite atoms of the draw history

The approved history is the pullback of the discrete sigma algebra under
the finite vector of preceding draws. Agreement of these draws determines
the remaining labels and their proportional-choice probabilities.
-/

namespace Luce

/-- The complete vector of the first `m` draws. -/
def prefixVector {n : ℕ} (σ : Equiv.Perm (Fin n)) (m : ℕ) :
    {j : Fin n // j.val < m} → Fin n := fun j => σ j.val

/-- The approved sigma algebra is exactly that generated by the finite
prefix vector, whose codomain carries the discrete sigma algebra. -/
theorem drawHistory_eq_comap_prefixVector {Ω : Type*} {n : ℕ}
    (π : Ω → Equiv.Perm (Fin n)) (m : ℕ) :
    drawHistory π m = MeasurableSpace.comap (fun ω => prefixVector (π ω) m) ⊤ := by
  classical
  let : MeasurableSpace (Fin n) := ⊤
  have htop : (inferInstance : MeasurableSpace ({j : Fin n // j.val < m} → Fin n)) = ⊤ :=
    top_unique (fun _ _ => MeasurableSet.of_discrete)
  rw [← htop]
  simp only [prefixVector, MeasurableSpace.comap_process_pi, drawHistory, iSup_subtype]
  rfl

/-- The finite prefix vectors are equal exactly when all corresponding
preceding draws agree. -/
theorem prefixVector_eq_iff {n : ℕ} (σ τ : Equiv.Perm (Fin n)) (m : ℕ) :
    prefixVector σ m = prefixVector τ m ↔
      ∀ j : Fin n, j.val < m → σ j = τ j := by
  constructor
  · intro h j hj
    exact congrFun h ⟨j, hj⟩
  · intro h
    funext j
    exact h j.val j.property

/-- Availability of every label is fixed by the preceding draw vector. -/
theorem remaining_eq_of_prefix_agreement {n : ℕ} (σ τ : Equiv.Perm (Fin n))
    (k : Fin n) (hprefix : ∀ j : Fin n, j < k → σ j = τ j) :
    remaining σ k = remaining τ k := by
  ext i
  simp only [remaining, Finset.mem_filter, Finset.mem_univ, true_and,
    inverse_ge_iff_no_earlier_draw]
  constructor <;> intro h j hj
  · simpa only [← hprefix j hj] using h j hj
  · simpa only [hprefix j hj] using h j hj

/-- The proportional chance is constant on each atom of the preceding
draw history. -/
theorem predictableChance_eq_of_prefix_agreement {n : ℕ} (w : Weights n)
    (σ τ : Equiv.Perm (Fin n)) (k : Fin n)
    (hprefix : ∀ j : Fin n, j < k → σ j = τ j) :
    predictableChance w σ k = predictableChance w τ k := by
  unfold predictableChance
  rw [remaining_eq_of_prefix_agreement σ τ k hprefix]

end Luce
