import Luce.Section1Model
import Mathlib.MeasureTheory.Constructions.BorelSpace.Real
import Mathlib.MeasureTheory.MeasurableSpace.Constructions

/-! # The approved history of a finite permutation

Source: `fixed_points.tex:569-579`, Section 2. This definition is exactly the
one approved in `proposals/Section2Predictability.lean`. A zero-based position
`j` has been observed after `m` draws precisely when `j.val < m`.
-/

open MeasureTheory
universe u

namespace Luce

/-- The sigma algebra generated by the first `m` draws, using the discrete
sigma algebra on the finite label set. -/
def drawHistory {Ω : Type u} {n : ℕ}
    (π : Ω → Equiv.Perm (Fin n)) (m : ℕ) : MeasurableSpace Ω :=
  ⨆ j : Fin n, ⨆ (_ : j.val < m),
    MeasurableSpace.comap (fun ω => π ω j) ⊤

end Luce
